name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate EmailJS configuration
      run: |
        mkdir -p src/environments
        echo "export const EMAILJS_KEYS = {
          serviceId: '${{ secrets.EMAILJS_SERVICE_ID }}',
          templateId: '${{ secrets.EMAILJS_TEMPLATE_ID }}',
          publicKey: '${{ secrets.EMAILJS_PUBLIC_KEY }}'
        };" > src/environments/emailjs-keys.ts
    
    - name: Build
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
